spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: ookk
    url: jdbc:mysql://localhost:3306/springcloudtest?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
  jpa:
    show-sql: true
  redis:
    host: 192.168.99.100
    port: 6379
 


# eureka:
#   client:
#     service-url:
#      defaultZone: http://discovery1:8761/eureka/
# PRODUCT:
#   ribbon:
#     NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
env:
  test110
girl:
  name: wc
  age: 1201
  
