spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: UIuYIU
    password: 3207423rherhu
    url: jdbc:mysql://localhost:3306/springcloudtest?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
  jpa:
    show-sql: true

# eureka:
#   client:
#     service-url:
#      defaultZone: http://discovery1:8761/eureka/
PRODUCT:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
